services:
  server:
    container_name: server-core
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
            python manage.py wait_for_db &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            gunicorn app.wsgi:application --bind 0.0.0.0:9000 --workers 3 --timeout 120
      "
    volumes:
      - ./:/server
    env_file:
      .env
    ports:
      - "9000:9000"
    networks:
      - microservices-net
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: db-core
    image: postgres:16.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-db-core}
      POSTGRES_USER: ${DB_USER:-dev}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pass}
    volumes:
      - core_data:/var/lib/postgresql/data
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-dev} -d ${DB_NAME:-db-core}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  core_data:



networks:
  microservices-net:
    external: true
